name: check-commits

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    container:
      image: rust:1.87

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}

      - name: Set Git safe.directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Verify commits message format
        run: |
          git log --pretty=format:"%s" |
          grep -vE "^(feat|fix|build|chore|docs|style|refactor|test|perf)\: " &&
          echo "❌ Invalid commit message format." && exit 1 || echo "✅ Commit messages are valid."

      - name: Check formatting
        run: |
            rustup component add rustfmt
            cargo fmt --check
